name: Tests

on:
  push:
    branches:
      - dev
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', 8.1, 8.2]

    name: PHP ${{ matrix.php }}
    
    services:

      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Verify MySQL connection
        run: |
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uuser -psecret -e "SHOW DATABASES"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: cd src && composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example src/.env

      - name: Generate app key
        run: cd src && php artisan key:generate
        
      - name: NPM Run Build
        run: cd src && npm install && npm run build
        
      - name: Run Testsuite
        run: cd src && vendor/bin/phpunit tests/
