name: Tests

on:
  push:
    branches:
      - dev
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', 8.1, 8.2]

    name: PHP ${{ matrix.php }}
    
    services:

      mariadb:
        image: mariadb:latest
        tty: true
        ports:
          - ${MARIADB_IP}:3306
        environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
        volumes:
          - ./src/storage/mysql/:/var/lib/mysql
        networks:
          - laravel

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate
        
      - name: Run Testsuite
        run: vendor/bin/phpunit tests/

      - name: NPM Run Build
        run: npm install && npm run build
